config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:  { registrations: 'users/registrations',
                                      omniauth_callbacks: 'users/callbacks' },
                      skip:         [:sessions]
  as :user do
    get '/users/sign_up',      to: 'devise/sessions#new',            as: :new_user_session
    get '/users/sign_out',     to: 'devise/sessions#destroy'
    post '/users/sign_in',     to: 'devise/sessions#create',         as: :user_session
    delete '/users/sign_out',  to: 'devise/sessions#destroy',        as: :destroy_user_session
    get '/users/signed_up',    to: 'users/registrations#signed_up',  as: :signed_up
  end

  resources :users, only: [:edit, :update] do
    post :ask_access
  end

  resources :facilities, only: [:show, :edit, :update] do
    resources :pets, only: [:new, :create, :edit, :update, :show] do
      post :adopt
    end
  end

  resources :states, only: [:show]

  get 'pets/search', to: 'pets#search'
  get 'pets/advanced_search_form', to: 'pets#advanced_search_form'

  get 'terms', to: 'statics#terms'
  get 'privacy', to: 'statics#privacy'
  get 'contacts', to: 'statics#contacts'

  root 'pets#index'
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  extend FriendlyId
  friendly_id :breed_and_name, use: [:slugged, :scoped], scope: :facility

  belongs_to :animal, polymorphic: true, dependent: :destroy
  belongs_to :facility
  has_many :pet_pictures, dependent: :destroy

  accepts_nested_attributes_for :animal
  accepts_nested_attributes_for :pet_pictures, reject_if: :all_blank, allow_destroy: true

  alias_attribute :pictures, :pet_pictures
  alias_attribute :pictures=, :pet_pictures=

  validates :name, :birth, :facility, :pet_pictures, presence: true
  validates :color, inclusion: { in: 0..25 }
  validates_associated :facility

  searchkick

  def self.search_params(params)
    attrs = cleanup(params)
    if attrs.key?(:advanced_search)
      advanced_search = cleanup(attrs[:advanced_search])
      advanced_search[:birth] = birth_range(advanced_search[:birth]) if advanced_search[:birth]
      advanced_search[:weight] = weight_range(advanced_search[:weight]) if advanced_search[:weight]
      advanced_search[:breeds] = [advanced_search[:breeds]] if advanced_search[:breeds]
      advanced_search = advanced_search.delete_if { |k, v| k == :heart && v == 'false' }
      { where: advanced_search }.deep_symbolize_keys
    else
      attrs.deep_symbolize_keys[:q]
    end
  end

  def self.cleanup(params)
    params.select { |_k, v| !v.blank? }
  end

  def self.birth_range(age)
    { lte: age.years.ago, gte: (age + 1).years.ago }
  end

  def self.weight_range(weight)
    from, to = weight.split('-')
    to.nil? ?
      { lte: (from.delete('+') + 15).to_i, gte: from.delete('+').to_i } :
      { lte: to.to_i, gte: from.to_i }
  end

  def search_data
    { name: name,
      birth: birth,
      gender: gender,
      color: color,
      weight: weight,
      heart: heart,
      size_at_maturity: animal.size_at_maturity,
      fur_length: animal.fur_length,
      spayed: animal.spayed,
      vaccinated: animal.vaccinated,
      breed: animal.decorate.breed,
      breeds: animal.mixtures.collect { |m| m.breed.id },
      facility: facility.name,
      state: facility.state.name }
  end

  def main_picture
    pictures.where(main: true).first
  end

  def build_animal(params)
    self.animal = Dog.new(params)
  end

  def description=(content)
    if content == '<p><br></p>'
      super('')
    else
      super(content)
    end
  end

  def breed_and_name
    "#{animal.mixtures.collect { |m| m.breed.name }.join(' ')} #{name}"
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :advanced_search_form]
  after_action :verify_authorized, except: [:index, :show, :search, :advanced_search_form, :adopt]

  def show
    @dog = Pet.friendly.find(params[:id]).animal.decorate
  end

  def search
    @response = Pet.search(Pet.search_params(params))
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @facility = Facility.friendly.find(params[:facility_id])
    @pet = @facility.construct_pet(:dog)
    authorize @pet
  end

  def create
    @facility = Facility.friendly.find(params[:facility_id])
    @pet = @facility.pets.create(secure_params)
    authorize @pet
    if @pet.valid?
      redirect_to facility_pet_path(
        facility_id: @pet.facility.slug, id: @pet.slug)
    else
      render :new, facility_id: @facility.slug
    end
  end

  def edit
    @facility = Facility.friendly.find(params[:facility_id])
    @pet = Pet.friendly.find(params[:id])
    authorize @pet
  end

  def update
    @facility = Facility.friendly.find(params[:facility_id])
    @pet = Pet.friendly.find(params[:id])
    authorize @pet
    if @pet.update_attributes(secure_params)
      redirect_to facility_pet_path(
        facility_id: @pet.facility.slug, id: @pet.slug)
    else
      render :edit, facility_id: @facility.slug, id: @pet.slug
    end
  end

  def adopt
    facility = Facility.friendly.find(params[:facility_id])
    pet = Pet.friendly.find(params[:pet_id])
    UserMailer.adopt(facility, pet, current_user, params[:adopt][:body]).deliver_now
    flash[:notice] = I18n.translate('adopt_message').capitalize
    redirect_to facility_pet_path(facility_id: facility.slug, id: pet.slug)
  end

  private

  def secure_params
    params.require(:pet).permit([
      :name, :description, :birth, :gender, :color, :weight, :facility_id,
      :heart, pet_pictures_attributes: [:photo_file, :caption, :id, :_destroy],
              animal_attributes: [
                :spayed, :dewormed, :microchipped, :vaccinated, :fur_length, :id, :size_at_maturity,
                mixtures_attributes: [:input_name, :percentage, :id, :_destroy]]])
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_adopt.html.haml
#adopt.modal.fade{role: 'dialog', tabindex: '-1'}
  .modal-dialog{:role => "document"}
    #ask-access-content.modal-content
      .modal-header
        %a.close{'data-dismiss': 'modal'} x
        %h3 Vuoi adottare?

      #adopt-body.modal-body
        %p
          Ricordati di includere:
          %ol
            %li Il tuo nome reale
            %li Il tuo numero di telefono
            %li La tua posizione geografica
          questi dati
          %strong non verranno registrati da PetsWantPats
          ma saranno ad uso esclusivo della struttura che ospita l'animale a cui sei interessato

        = form_for :adopt, url: facility_pet_adopt_path(facility_id: pet.facility.slug, pet_id: pet.slug) do |f|
          .row
            .col-sm-6
              .form-group
                = f.label :body, 'Messaggio'
                = f.text_area :body, rows: 10, required: true, class: 'form-control message'

          .modal-footer
            %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'}
              Cancella
            = f.submit 'Manda messaggio', class: 'button btn btn-primary'

app/views/pets/_form.html.haml
= render partial: 'shared/errors', locals: {object: form.object}
= form.hidden_field :facility_id, value: @facility.id
.row
  .col-sm-6
    .form-group
      = form.input :name, label: 'Nome', class: 'form-control', error: 'Deve avere un nome'
  .col-sm-6
    .form-group
      = form.input :birth, as: :date, label: 'Nascita', start_year: Date.today.year - 18,
        end_year: Date.today.year, discard_day: true, class: 'form-control', error: 'Indicare la data di nascita'
.row
  .col-sm-3
    .form-group
      = form.input :gender, label: I18n.translate('gender').capitalize, collection: [true, false].collect { |n| [I18n.translate(:genders)[n].capitalize, n] }, required: true, error: 'Indicare il sesso'
  .col-sm-3
    .form-group
      = form.input :color, label: I18n.translate('color').capitalize, collection: (0..26).collect { |n| [I18n.translate(:colors)[n].capitalize, n] }, required: true, error: 'Indicare il colore del manto'
  .col-sm-3
    .form-group
      = form.input :weight, label: I18n.translate('weight').capitalize, as: :float, input_html: {step: 0.5}, required: true
  = form.simple_fields_for :animal do |dog|
    .col-sm-3
      .form-group
        = dog.input :size_at_maturity, label: I18n.translate('dog.size_at_maturity').capitalize, collection: (0..2).collect { |n| [I18n.translate(:size_at_maturity)[n].capitalize, n] }, required: true, error: 'Indicare la taglia'
.row
  = form.simple_fields_for :animal do |dog|
    .col-sm-3
      .form-group
        = dog.input :spayed, label: I18n.translate('dog.spayed').capitalize, as: :boolean, required: true
    .col-sm-3
      .form-group
        = dog.input :dewormed, label: I18n.translate('dog.dewormed').capitalize, as: :boolean, required: true
    .col-sm-3
      .form-group
        = dog.input :microchipped, label: I18n.translate('dog.microchipped').capitalize, as: :boolean, required: true
    .col-sm-3
      .form-group
        = dog.input :vaccinated, label: I18n.translate('dog.vaccinated').capitalize, as: :boolean, required: true
%hr

.row
  .col-sm-12
    %p
      Se l'animale presenta particolari difficoltà di gestione in seguito a disabilità o un carattere particolarmente difficile contrassegnare questa opzione,
      %strong ricordandosi di specificare nella descrizione le problematiche dell'animale.
    .form-group
      = form.input :heart, label: 'Adozione del cuore', as: :boolean, required: true
.row
  .col-sm-8
    .form-group
      = form.label :description, 'Descrizione'
      = form.text_area :description, id: 'summernote', class: 'summernote form-control', 'data-provider': 'summernote'
  .col-sm-4
    .form-group
      = form.simple_fields_for :animal do |dog|
        = dog.input :fur_length, label: I18n.translate('dog.fur_length').capitalize, collection: (0..2).collect { |n| [I18n.translate(:fur_length)[n].capitalize, n] }, required: false

%hr

%p Puoi creare una galleria del tuo animale.
%p Cerca di inserire fotografie di buona qualità per invogliare eventuali adottanti.
#pet_pictures
  = form.simple_fields_for :pet_pictures do |pet_picture|
    = render partial: 'pet_pictures/pet_picture_fields', locals: {f: pet_picture}
  .links
    = link_to_add_association form, :pet_pictures, partial: 'pet_pictures/pet_picture_fields', 'data-association-insertion-method': :before, class: 'btn btn-default', id: 'add_pet_image' do
      %i.fa.fa-file-image-o
      Aggiungi immagine

%hr

%p Puoi aggiungere una razza reale e presunta al tuo animale.
%p Se stai per esempio inserendo la scheda di un cane che è un incrocio tra un maremmano ed un labrador puoi indicare questa caratteristica aggiungendo due razze: 50% maremmano e 50% labrador.
#mixtures
  = form.fields_for :animal do |dog|
    = dog.fields_for :mixtures do |mixture|
      = render partial: 'mixtures/mixture_fields', locals: {f: mixture}
    .links
      = link_to_add_association dog, :mixtures, partial: 'mixtures/mixture_fields', 'data-association-insertion-method': :before, class: 'btn btn-default' do
        %i.fa.fa-plus
        Aggiungi una razza

%hr

app/views/pets/_manage.html.haml
%h3
  =link_to '#', class: 'dropdown dropdown-toggle', 'data-toggle': 'dropdown' do
    %i.fa.fa-pencil-square-o
    = pet.name
    .caret

  %ul.dropdown-menu.pull-right
    %li
      = link_to I18n.translate('dog.show').capitalize, facility_pet_path(facility_id: pet.facility.slug, id: pet.slug)
    %li
      = link_to I18n.translate('dog.adopted').capitalize, '#'
    %li
      = link_to I18n.translate('dog.manage').capitalize, edit_facility_pet_path(facility_id: pet.facility.slug, id: pet.slug), class: 'edit_pet'
    %li
      = link_to I18n.translate('dog.remove').capitalize, '#'

app/views/pets/_pet.html.haml
.col-md-3.col-sm-4
  .product
    .image
      =link_to facility_pet_path(facility_id: pet.facility.slug, id: pet.slug) do
        =image_tag pet.main_picture.photo_file.listing.url
    - if current_user && current_user.has_role?(:owner, pet.facility)
      = render partial: 'pets/manage', locals: {pet: pet}
    - else
      %h3= link_to pet.name, facility_pet_path(facility_id: pet.facility.slug, id: pet.slug)

app/views/pets/_pets.html.haml
#pets
  .row.products
    = render pets

  = paginate pets, remote: true

app/views/pets/edit.html.haml
#all
  #content
    .container
      .col-md-12
        %ul.breadcrumb
          %li
            = link_to 'Home', root_url
          %li
            = link_to @facility.name, facility_path(@facility.slug)
          %li
            = link_to @pet.name, facility_pet_path(facility_id: @facility.slug, id: @pet.slug)
          %li Gestisci
      .col-md-12
        .box
          %h1= @facility.name
          %p.lead Aggiorna i dati
          %p Modifica nel form sottostante le informazioni dell'animale in adozione.
          %hr/
          = simple_form_for(@pet,
            url: facility_pet_path(facility_id: @facility.slug, id: @pet.slug),
            html: {multipart: true}) do |form|
            = render partial: 'form', locals: {form: form}
            .text-center
              %button.btn.btn-primary{:type => "submit"}
                %i.fa.fa-user
                Aggiorna

app/views/pets/index.html.haml
#all
  #content
    #claim
      #bg-video
        %video{autoplay: true, autobuffer: true, loop: true, mute: true, controls: false, id: 'video'}
          %source{src: 'https://s3.eu-central-1.amazonaws.com/petswantpats/hp.mp4', type: 'video/mp4'}
          %source{src: 'https://s3.eu-central-1.amazonaws.com/petswantpats/hp.webm', type: 'video/webm'}
          %source{src: 'https://s3.eu-central-1.amazonaws.com/petswantpats/hp.ogv', type: 'video/ogg'}
          = image_tag 'hp.png'
      #hp_search
        .col-md-12
          %h3.hidden-xs.hidden-sm Vuoi trovare un tesoro?
          %h2.hidden-xs.hidden-sm Cerca un amico!
          = form_tag pets_search_path, method: :get, class: 'navbar-form', role: 'search' do
            .input-group
              = text_field_tag :q, nil, label: nil, required: true, placeholder: 'Cerca (per nome, razza, regione, colore)', class: 'form-control input-lg'
              %span.input-group-btn
                %button.btn-lg.btn-primary{ type: 'submit' }
                  %i.fa.fa-search
                  %span.hidden-xs.hidden-sm Ricerca
          %p Motore di ricerca per animali da compagnia ospitati nei canili e rifugi italiani.
          %p.hidden-xs.hidden-sm
            - if !user_signed_in?
              =link_to 'Vuoi inserire i tuoi animali su PetsWantPats per farli adottare?', new_user_registration_path
            - else
              =link_to 'Vuoi inserire i tuoi animali su PetsWantPats per farli adottare?', edit_user_path(current_user.slug)

app/views/pets/new.html.haml
#all
  #content
    .container
      .col-md-12
        %ul.breadcrumb
          %li
            = link_to 'Home', root_url
          %li
            = link_to @facility.name, facility_path(@facility.slug)
          %li Aggiungi animale
      .col-md-12
        .box
          %h1= @facility.name
          %p.lead Aggiungi un animale
          %p Inserisci nel form sottostante le informazioni dell'animale in adozione.
          %hr/
          = simple_form_for(@pet, url: facility_pets_path, html: {multipart: true}) do |form|
            = render partial: 'form', locals: {form: form}

            .text-center
              %button.btn.btn-primary{:type => "submit"}
                %i.fa.fa-user
                Aggiungi

app/views/pets/pets.js.haml
$('#pets').html("#{escape_javascript(render(partial: 'pets/pets', locals: {pets: @pets}))}");

app/views/pets/search.html.haml
#all
  #content
    .container
      .col-md-12
        %ul.breadcrumb
          %li
            = link_to 'Home', root_url
          %li Ricerca
        .row
          .box.text-center
            .row
              .col-sm-10.col-sm-offset-1
                %h1 Ricerca
                %p.text-muted
                  = "Hai cercato #{params['q']}"
      .box.info-bar.full-width.no-border
        .row
          .col-sm-12.col-md-4.products-showing
            Mostrando
            %strong= @response.results.count
            di
            %strong= @response.total_count
            risultati
          .col-sm-12.col-md-8.products-number-sort
            .row
              %form.form-inline
                .col-md-offset-6.col-sm-offset-6
                  .products-sort-by
                    %strong Ordina per
                    %select#order-by.form-control{name: 'sort-by'}
                      %option{name: 'birth'} Età
                      %option{name: 'weight'} Peso
      .row.products
        = render partial: 'pets', locals: {pets: @response}

app/views/pets/search.js.haml
$('#pets').html("#{escape_javascript(render(partial: 'pets/pets', locals: {pets: @response}))}");

app/views/pets/show.html.haml
= render partial: 'headers/pet_show'
#all
  #content
    .container
      .col-md-12      
        %ul.breadcrumb
          %li
            = link_to 'Home', root_url
          %li
            = link_to @dog.pet_facility.name, facility_path(@dog.pet_facility.slug)
          %li
            = @dog.pet_name
        .box.text-center
          .row
            .col-sm-10.col-sm-offset-1
              %h1= @dog.pet_name
              %p.text-muted= @dog.pet_description.try(:html_safe)
              %p.goToDescription
                %a.scroll-to{:href => "#details"} Dettagli dell'animale
              #product-social.social
                .row
                  %h4 Mostralo ai tuoi amici
                  .col-md-6.col-md-offset-3
                    = render partial: 'shared/share'
              %button.adopt.btn.btn-primary.btn-lg{'data-target': '#adopt', 'data-toggle': 'modal', type: 'button'}
                %i.glyphicon.glyphicon-heart
                #{I18n.translate('adopt').capitalize}!
      .col-md-12
        #productMain.row
          .col-sm-4
            #mainImage
              = image_tag(@dog.pet.main_picture.photo_file.url, class: 'img-responsive')
          .col-sm-8
            #thumbs.row
              - @dog.pet.pictures.each do |picture|
                .col-xs-4
                  = link_to picture.photo_file.url, class: 'thumb' do
                    = image_tag(picture.photo_file.url, class: 'img-responsive')
        #details.box
          %p.description= @dog.pet_description.try(:html_safe)
          .table-responsive
            %table.table.table-striped
              %tbody
                %tr
                  %td
                    %strong= I18n.translate('location').capitalize
                  %td
                    = link_to facility_path(@dog.pet_facility.slug) do
                      = @dog.pet_facility.name
                      %br
                      = @dog.pet_facility.full_address_with_state
                %tr
                  %td
                    %strong= I18n.translate('dog.breed').capitalize
                  %td= @dog.breed
                %tr
                  %td
                    %strong= I18n.translate('color').capitalize
                  %td= @dog.color.capitalize
                %tr
                  %td
                    %strong= I18n.translate('dog.size_at_maturity').capitalize
                  %td= @dog.size_at_maturity.capitalize
                %tr
                  %td
                    %strong= I18n.translate('dog.fur_length').capitalize
                  %td= @dog.fur_length.capitalize
                %tr
                  %td
                    %strong= I18n.translate('gender').capitalize
                  %td= @dog.gender.capitalize
                %tr
                  %td
                    %strong= I18n.translate('weight').capitalize
                  %td= @dog.pet_weight
                %tr
                  %td
                    %strong= I18n.translate('dog.spayed').capitalize
                  %td= @dog.spayed.capitalize
                %tr
                  %td
                    %strong= I18n.translate('dog.dewormed').capitalize
                  %td= @dog.dewormed.capitalize
                %tr
                  %td
                    %strong= I18n.translate('dog.vaccinated').capitalize
                  %td= @dog.vaccinated.capitalize
                %tr
                  %td
                    %strong= I18n.translate('dog.microchipped').capitalize
                  %td= @dog.microchipped.capitalize

          .col-sm-10.col-sm-offset-1
            #product-social.social
              .row
                %h4 Mostralo ai tuoi amici
                .col-md-6.col-md-offset-3
                  = render partial: 'shared/share'
            %button.adopt.btn.btn-primary.btn-lg{'data-target': '#adopt', 'data-toggle': 'modal', type: 'button'}
              %i.glyphicon.glyphicon-heart
              #{I18n.translate('adopt').capitalize}!

          = render partial: 'pets/adopt', locals: {facility: @dog.pet_facility, pet: @dog.pet}