config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:  { registrations: 'users/registrations',
                                      omniauth_callbacks: 'users/callbacks' },
                      skip:         [:sessions]
  as :user do
    get '/users/sign_up',      to: 'devise/sessions#new',            as: :new_user_session
    get '/users/sign_out',     to: 'devise/sessions#destroy'
    post '/users/sign_in',     to: 'devise/sessions#create',         as: :user_session
    delete '/users/sign_out',  to: 'devise/sessions#destroy',        as: :destroy_user_session
    get '/users/signed_up',    to: 'users/registrations#signed_up',  as: :signed_up
  end

  resources :users, only: [:edit, :update] do
    post :ask_access
  end

  resources :facilities, only: [:show, :edit, :update] do
    resources :pets, only: [:new, :create, :edit, :update, :show] do
      post :adopt
    end
  end

  resources :states, only: [:show]

  get 'pets/search', to: 'pets#search'
  get 'pets/advanced_search_form', to: 'pets#advanced_search_form'

  get 'terms', to: 'statics#terms'
  get 'privacy', to: 'statics#privacy'
  get 'contacts', to: 'statics#contacts'

  root 'pets#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  resourcify
  rolify

  extend FriendlyId
  friendly_id :username, use: :slugged

  belongs_to :state

  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader, validate_download: false

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      extract_from_fb_auth(user, auth)
    end
  end

  def self.extract_from_fb_auth(user, auth)
    user.email = auth.info.email
    user.first_name = auth.info.first_name
    user.last_name = auth.info.last_name
    user.location = auth.info.location
    user.gender = extract_fb_gender(auth)
    user.birthday = extract_fb_birthday(auth)
    user.password = Devise.friendly_token[0, 8]
  end

  def self.extract_fb_gender(auth)
    unless auth.extra.raw_info.gender.nil?
      (auth.extra.raw_info.gender == 'uomo') ? false : true
    end
  end

  def self.extract_fb_birthday(auth)
    unless auth.extra.raw_info.birthday.nil?
      Date.strptime(auth.extra.raw_info.birthday, '%m/%d/%Y')
    end
  end

  def facilities
    if has_role?(:owner, :any)
      roles.where(resource_type: 'Facility').collect(&:resource)
    else
      []
    end
  end
end

app/controllers/users/callbacks_controller.rb
module Users
  class CallbacksController < ApplicationController
    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        flash[:notice] = 'Ti sei autenticato con successo'
      else
        render
      end
    end

    def failure
      flash[:error] = 'Autorizzazione non riuscita, ritenta.'
      redirect_to new_registration_path
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def sign_up_params
      params.require(:user).permit([
        :username, :avatar, :uid, :provider, :email, :first_name,
        :last_name, :location, :state_id, :gender, :birthday, :password,
        :password_confirmation
      ])
    end

    def after_inactive_sign_up_path_for(_resource)
      '/users/signed_up'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def edit
    @user = User.friendly.find(params[:id])
    authorize @user
  end

  def update
    @user = User.friendly.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to root_path, notice: I18n.t('devise.registrations.updated')
    else
      redirect_to edit_user_registration_path
    end
  end

  def ask_access
    @user = User.friendly.find(params[:user_id])
    authorize @user
    UserMailer.ask_access(current_user, params[:ask_access][:body]).deliver_now
    respond_to do |format|
      format.js { render }
    end
  end

  protected

  def secure_params
    params.require(:user).permit([
      :username, :avatar, :uid, :provider, :first_name, :last_name,
      :location, :state_id, :gender, :birthday])
  end
end

app/views/users/_account.html.haml
#account.tab-pane.active
  .row.text-center
    .col-sm-10.col-sm-offset-1
      %h1 Il mio account
      %p.lead Cambia i tuoi dati personali e la tua password qui.
  #customer-account.col-md-8.col-md-offset-2.clearfix
    %h3= current_user.username
    = form_for current_user, method: :put do |f|
      = render partial: 'users/common', locals: {user: current_user, form: f}
      .row
        .col-sm-6
          .form-group
            = f.label :password, 'Nuova password'
            = f.password_field :password, autocomplete: "off", class: 'form-control'
        .col-sm-6
          .form-group
            = f.label :password_confirmation, 'Conferma nuova password'
            = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'
      .text-center
        %button.btn.btn-primary{id: 'update_user', type: 'submit'}
          %i.fa.fa-save
          Aggiorna

app/views/users/_ask_access.html.haml
#ask-access.modal.fade{role: 'dialog', tabindex: '-1'}
  .modal-dialog{:role => "document"}
    #ask-access-content.modal-content
      .modal-header
        %a.close{'data-dismiss': 'modal'} x
        %h3 Richiedi un accesso privilegiato

      #ask-access-body.modal-body
        %p
          Ricordati di includere il
          %strong nome della struttura,
          la sua
          %strong ubicazione geografica
          (indirizzo, città), e possibilmente
          %strong il nome e l'indirizzo di un responsabile.

        = form_for :ask_access, url: user_ask_access_url(current_user.slug), remote: true do |f|
          .row
            .col-sm-6
              .form-group
                = f.label :body, 'Messaggio'
                = f.text_area :body, rows: 10, required: true, class: 'form-control message'

          .modal-footer
            %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'}
              Cancella
            = f.submit 'Manda messaggio', class: 'button btn btn-primary'

app/views/users/_common.html.haml
.row
  .col-sm-6
    .form-group
      = form.label :avatar
      = form.file_field :avatar, class: 'form-control'
  .col-sm-6
    = image_tag user.avatar.thumb.url, size: '128x128'
.row
  .col-sm-6
    .form-group
      = form.label :email
      = form.email_field :email, required: true, autofocus: true, class: 'form-control'
.row
  .col-sm-6
    .form-group
      = form.label :first_name, 'Nome'
      = form.text_field :first_name, class: 'form-control'
  .col-sm-6
    .form-group
      = form.label :last_name, 'Cognome'
      = form.text_field :last_name, class: 'form-control'
.row
  .col-sm-6
    .form-group
      = form.label :location, 'Residenza'
      = form.text_field :location, class: 'form-control'
  .col-sm-6
    .form-group
      = form.label :state_id, 'Regione'
      = form.select :state_id, State.all.order(:name).collect {|state| [state.name, state.id]}, {include_blank: true}, {class: 'form-control'}
.row
  .col-sm-6
    .form-group
      = form.label :birthday, 'Data di Nascita'
      = form.date_field :birthday, class: 'form-control'
.row
  .col-sm-6
    .form-group.radios
      .col-sm-6
        = form.radio_button :gender, true
        = form.label :gender, 'Donna'
      .col-sm-6
        = form.radio_button :gender, false
        = form.label :gender, 'Uomo'

.row
  .col-sm-6
    .form-group
      = form.label :username
      = form.text_field :username, required: true, class: 'form-control'
  .col-sm-6
    %p.instruction Questo è il nome che vuoi usare all'interno della comunità.

app/views/users/_thanks_for_asking_access.html.haml
.modal-body
  %h4 Grazie per la richiesta.
  %p
    Un membro del team di
    %strong PetsWantPats
    ti contatterà al più presto, quindi ti chiediamo di portare pazienza.

app/views/users/ask_access.js.haml
$('#ask-access-body').html("#{escape_javascript(render(partial: 'users/thanks_for_asking_access', locals: {pets: @pets}))}");

app/views/users/edit.html.haml
#all
  #content.clearfix
    .container
      .col-md-12
        %ul.breadcrumb
          %li= link_to 'Home', root_url
          %li= current_user.username
        %ul.nav.nav-tabs{'data-tabs': 'tabs'}
          %li.active
            = link_to '#account', 'data-toggle': 'tab' do
              %i.fa.fa-user
              Account
          - current_user.facilities.each do |facility|
            %li
              = link_to "##{facility.slug}", 'data-toggle': 'tab' do
                %i.fa.fa-map-signs
                = facility.name
          %li
            = link_to '#facility', 'data-toggle': 'tab' do
              %i.fa.fa-plus
              Aggiungi una struttura
        .tab-content
          =render partial: 'users/account'
          =render partial: 'facilities/edit', collection: current_user.facilities, as: :facility
          =render partial: 'facilities/user_add'