config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:  { registrations: 'users/registrations',
                                      omniauth_callbacks: 'users/callbacks' },
                      skip:         [:sessions]
  as :user do
    get '/users/sign_up',      to: 'devise/sessions#new',            as: :new_user_session
    get '/users/sign_out',     to: 'devise/sessions#destroy'
    post '/users/sign_in',     to: 'devise/sessions#create',         as: :user_session
    delete '/users/sign_out',  to: 'devise/sessions#destroy',        as: :destroy_user_session
    get '/users/signed_up',    to: 'users/registrations#signed_up',  as: :signed_up
  end

  resources :users, only: [:edit, :update] do
    post :ask_access
  end

  resources :facilities, only: [:show, :edit, :update] do
    resources :pets, only: [:new, :create, :edit, :update, :show] do
      post :adopt
    end
  end

  resources :states, only: [:show]

  get 'pets/search', to: 'pets#search'
  get 'pets/advanced_search_form', to: 'pets#advanced_search_form'

  get 'terms', to: 'statics#terms'
  get 'privacy', to: 'statics#privacy'
  get 'contacts', to: 'statics#contacts'

  root 'pets#index'
end

app/views/shared/_advanced_search_form.html.haml
#advanced-search.collapse
  = simple_form_for :advanced_search, url: pets_search_path, method: :get, role: 'search' do |form|
    .row
      .col-sm-4
        .form-group
          = form.input :age, label: 'Età', as: :integer, input_html: {step: 1}, required: false
      .col-sm-4
        .form-group
          = form.input :breeds, label: 'Razza', collection: Breed.all.collect {|breed| [breed.name, breed.id]}, required: false
      .col-sm-4
        .form-group
          = form.input :weight, label: 'Peso', collection: ['0-5', '5-10', '10-20', '20-40', '40+'], required: false
    .row
      .col-sm-4
        .form-group
          = form.input :gender, label: 'Sesso', collection: [true, false].collect { |n| [I18n.translate(:genders)[n].capitalize, n] }, required: false
      .col-sm-4
        .form-group
          = form.input :color, label: 'Colore', collection: (0..25).collect { |n| [I18n.translate(:colors)[n].capitalize, n] }, required: false
      .col-sm-4
        .form-group
          = form.input :fur_length, label: 'Lunghezza del pelo', collection: (0..2).collect { |n| [I18n.translate(:fur_length)[n].capitalize, n] }, required: false
    .row
      .col-sm-offset-4.col-sm-4
        = form.label 'Adozioni del cuore', required: false
        = form.check_box :heart, {}, true, false
      .col-sm-4
        %span.input-group-btn
          %button.btn.btn-primary{ type: 'submit' }
            %i.fa.fa-search
            Ricerca

app/views/shared/_errors.html.haml
-if object.errors.any?
  .alert{:class => "alert-error"}
    %p= "Per favore correggi i seguenti errori:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.haml
#footer
  .container
    .col-md-3.col-sm-6.col-xs-6
      %ul
        %li
          = link_to 'Termini e condizioni', terms_path
        %li
          = link_to 'Policy sulla privacy', privacy_path
        %li
          = link_to 'Contattaci', contacts_path
    .col-md-3.col-md-offset3.col-sm-6.col-sm-offset-6.col-xs-6.col-xs-offset6
      %h4 Stay in touch
      %p.social
        %a{href: 'https://www.facebook.com/petswantpats/'}
          %i.fa.fa-facebook-square
        %a{href: 'https://twitter.com/petswantpats/'}
          %i.fa.fa-twitter-square
        %a{href: 'mailto:lola@petswantpats.com'}
          %i.fa.fa-envelope

app/views/shared/_gtm.html.haml
/ Google Tag Manager
%noscript
  %iframe{:height => "0", :src => "//www.googletagmanager.com/ns.html?id=GTM-NXTSNB", :style => "display:none;visibility:hidden", :width => "0"}
:javascript
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-NXTSNB');
/ End Google Tag Manager

app/views/shared/_messages.html.haml
-if notice
  .alert.alert-info{ role: 'alert' }
    %i.fa.fa-info-circle
    =notice

-if alert
  .alert.alert-danger{ role: 'alert' }
    %i.fa.fa-exclamation-triangle
    =alert

app/views/shared/_navbar.html.haml
#navbar.navbar.navbar-default.navbar-fixed-top.yamm{:role => "navigation"}
  .container
    .navbar-header
      =link_to root_path, class: 'navbar-brand home' do
        = image_tag 'pwp_logo.png', alt: 'PetsWantPats logo', class: 'hidden-xs hidden-sm'
        = image_tag 'pwp_logo_small.png', alt: 'PetsWantPats logo', class: 'visible-xs visible-sm'
        %span.sr-only PetsWantPats - go to homepage
      .navbar-buttons
        %button.navbar-toggle.btn-primary{"data-target" => "#navigation", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %i.fa.fa-align-justify
        - if !current_page?(root_path)
          %button.navbar-toggle.btn-default{"data-target" => "#search", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle search
            %i.fa.fa-search
        - if !user_signed_in?
          =link_to new_user_registration_path, class: 'btn navbar-toggle btn-default' do
            %span.sr-only Registrati/Accedi
            %i.fa.fa-users
        - else
          =link_to edit_user_path(current_user.slug), class: 'btn navbar-toggle btn-default' do
            %span.sr-only= current_user.username
            %i.fa.fa-users
          =link_to destroy_user_session_path, method: :delete, class: 'btn navbar-toggle btn-default' do
            %span.sr-only Esci
            %i.fa.fa-sign-out
    #navigation.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-left
        %li.active
          = link_to 'Home', root_path
        %li.dropdown.yamm-fw
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Strutture
            %b.caret
          %ul.dropdown-menu
            %li
              .yamm-content
                .row
                  - State.that_has_facilities.decorate.each_slice(4) do |slice|
                    .col-sm-3
                      - slice.each do |state|
                        %ul
                          %li
                            =link_to state.name_with_facilities_number, state_path(state.slug)
    - if !user_signed_in?
      .navbar-collapse.collapse.right
        =link_to new_user_registration_path, class: 'btn navbar-btn btn-default' do
          %i.fa.fa-users
          Registrati/Accedi
    - else
      .navbar-collapse.collapse.right
        =link_to edit_user_path(current_user.slug), class: 'btn navbar-btn btn-default' do
          %i.fa.fa-users
          =current_user.username
        =link_to destroy_user_session_path, method: :delete, class: 'btn navbar-btn btn-default' do
          %i.fa.fa-sign-out
          Esci
    - if !current_page?(root_path)
      .navbar-collapse.collapse.right
        %button.btn.navbar-btn.btn-default{"data-target": "#search", "data-toggle": "collapse", type: "button"}
          %span.sr-only Toggle search
          %i.fa.fa-search
          Ricerca
      = render partial: 'shared/search'

app/views/shared/_search.html.haml
#search.collapse.clearfix
  = form_tag pets_search_path, method: :get, class: 'navbar-form', role: 'search' do
    .input-group
      = text_field_tag :q, nil, label: nil, placeholder: 'Cerca (per nome, razza, regione)', class: 'form-control'
      %span.input-group-btn
        %button.btn.btn-primary{ type: 'submit' }
          %i.fa.fa-search
          Ricerca
  .col-md-4.col-md-offset-8
    .row
      = link_to 'Ricerca avanzata', '#advanced-search', 'data-toggle': 'collapse'
  .col-md-12
    = render partial: 'shared/advanced_search_form'

app/views/shared/_share.html.haml
%ul.rrssb-buttons.clearfix
  %li.rrssb-email
    / Replace subject with your message using URL Endocding: http://meyerweb.com/eric/tools/dencoder/
    %a{:href => "mailto:?#{{body: request.original_url}.to_query}"}
      %span.rrssb-icon
        %svg{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M20.11 26.147c-2.335 1.05-4.36 1.4-7.124 1.4C6.524 27.548.84 22.916.84 15.284.84 7.343 6.602.45 15.4.45c6.854 0 11.8 4.7 11.8 11.252 0 5.684-3.193 9.265-7.398 9.3-1.83 0-3.153-.934-3.347-2.997h-.077c-1.208 1.986-2.96 2.997-5.023 2.997-2.532 0-4.36-1.868-4.36-5.062 0-4.75 3.503-9.07 9.11-9.07 1.713 0 3.7.4 4.6.972l-1.17 7.203c-.387 2.298-.115 3.3 1 3.4 1.674 0 3.774-2.102 3.774-6.58 0-5.06-3.27-8.994-9.304-8.994C9.05 2.87 3.83 7.545 3.83 14.97c0 6.5 4.2 10.2 10 10.202 1.987 0 4.09-.43 5.647-1.245l.634 2.22zM16.647 10.1c-.31-.078-.7-.155-1.207-.155-2.572 0-4.596 2.53-4.596 5.53 0 1.5.7 2.4 1.9 2.4 1.44 0 2.96-1.83 3.31-4.088l.592-3.72z"}
      %span.rrssb-text email
  %li.rrssb-facebook
    / Replace with your URL. For best results, make sure you page has the proper FB Open Graph tags in header: https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/
    %a.popup{:href => "https://www.facebook.com/sharer/sharer.php?#{ {u: request.original_url}.to_query}"}
      %span.rrssb-icon
        %svg{:viewbox => "0 0 29 29", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M26.4 0H2.6C1.714 0 0 1.715 0 2.6v23.8c0 .884 1.715 2.6 2.6 2.6h12.393V17.988h-3.996v-3.98h3.997v-3.062c0-3.746 2.835-5.97 6.177-5.97 1.6 0 2.444.173 2.845.226v3.792H21.18c-1.817 0-2.156.9-2.156 2.168v2.847h5.045l-.66 3.978h-4.386V29H26.4c.884 0 2.6-1.716 2.6-2.6V2.6c0-.885-1.716-2.6-2.6-2.6z"}
      %span.rrssb-text facebook
  %li.rrssb-twitter
    / Replace href with your Meta and URL information
    %a.popup{:href => "https://twitter.com/intent/tweet?#{ {text: request.original_url}.to_query }"}
      %span.rrssb-icon
        %svg{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M24.253 8.756C24.69 17.08 18.297 24.182 9.97 24.62a15.093 15.093 0 0 1-8.86-2.32c2.702.18 5.375-.648 7.507-2.32a5.417 5.417 0 0 1-4.49-3.64c.802.13 1.62.077 2.4-.154a5.416 5.416 0 0 1-4.412-5.11 5.43 5.43 0 0 0 2.168.387A5.416 5.416 0 0 1 2.89 4.498a15.09 15.09 0 0 0 10.913 5.573 5.185 5.185 0 0 1 3.434-6.48 5.18 5.18 0 0 1 5.546 1.682 9.076 9.076 0 0 0 3.33-1.317 5.038 5.038 0 0 1-2.4 2.942 9.068 9.068 0 0 0 3.02-.85 5.05 5.05 0 0 1-2.48 2.71z"}
      %span.rrssb-text twitter
  %li.rrssb-googleplus
    / Replace href with your meta and URL information.
    %a.popup{:href => "https://plus.google.com/share?#{ {url: request.original_url}.to_query }"}
      %span.rrssb-icon
        %svg{:height => "24", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M21 8.29h-1.95v2.6h-2.6v1.82h2.6v2.6H21v-2.6h2.6v-1.885H21V8.29zM7.614 10.306v2.925h3.9c-.26 1.69-1.755 2.925-3.9 2.925-2.34 0-4.29-2.016-4.29-4.354s1.885-4.353 4.29-4.353c1.104 0 2.014.326 2.794 1.105l2.08-2.08c-1.3-1.17-2.924-1.883-4.874-1.883C3.65 4.586.4 7.835.4 11.8s3.25 7.212 7.214 7.212c4.224 0 6.953-2.988 6.953-7.082 0-.52-.065-1.104-.13-1.624H7.614z"}
      %span.rrssb-text google+
  %li.rrssb-pinterest
    / Replace href with your meta and URL information.
    %a{:href => "http://pinterest.com/pin/create/button/?#{ {url: request.original_url, description: (@dog.pet_description.blank? ? "#{I18n.translate('adopt')} #{@dog.pet_name} - #{@dog.breed} - #{@dog.pet_facility.full_address} - #{@dog.pet_facility.name}" : strip_tags(@dog.pet_description)) }.to_query }"}
      %span.rrssb-icon
        %svg{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M14.02 1.57c-7.06 0-12.784 5.723-12.784 12.785S6.96 27.14 14.02 27.14c7.062 0 12.786-5.725 12.786-12.785 0-7.06-5.724-12.785-12.785-12.785zm1.24 17.085c-1.16-.09-1.648-.666-2.558-1.22-.5 2.627-1.113 5.146-2.925 6.46-.56-3.972.822-6.952 1.462-10.117-1.094-1.84.13-5.545 2.437-4.632 2.837 1.123-2.458 6.842 1.1 7.557 3.71.744 5.226-6.44 2.924-8.775-3.324-3.374-9.677-.077-8.896 4.754.19 1.178 1.408 1.538.49 3.168-2.13-.472-2.764-2.15-2.683-4.388.132-3.662 3.292-6.227 6.46-6.582 4.008-.448 7.772 1.474 8.29 5.24.58 4.254-1.815 8.864-6.1 8.532v.003z"}
      %span.rrssb-text pinterest
  %li.rrssb-tumblr
    %a{:href => "http://tumblr.com/share/link?#{ {url: request.original_url}.to_query }"}
      %span.rrssb-icon
        %svg{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M18.02 21.842c-2.03.052-2.422-1.396-2.44-2.446v-7.294h4.73V7.874H15.6V1.592h-3.714c-.06 0-.167.053-.182.186-.218 1.935-1.144 5.33-4.988 6.688v3.637h2.927v7.677c0 2.8 1.7 6.7 7.3 6.6 1.863-.03 3.934-.795 4.392-1.453l-1.22-3.54c-.52.213-1.415.413-2.115.455z"}
      %span.rrssb-text tumblr